TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map 
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.5 
 dt_hysteresis: 0.2 
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 8.0      #1)5.0    2)5.0   3)3.0   4)8.0   5)8.0
 feasibility_check_no_poses: 5

 publish_feedback: true
    
 # Robot

 max_vel_x: 0.75           #1)0.6    2)0.6   3)0.2   4)0.9   5)0.75
 max_vel_x_backwards: 0.3
 max_vel_theta: 0.6       #1)0.6    2)0.6   3)0.8   4)0.3   5)0.6
 acc_lim_x: 0.7           #1)0.6    2)0.6   3)0.3   4)0.8   5)0.7
 acc_lim_theta: 0.6       #1)0.6    2)0.6   3)0.8   4)0.3   5)0.6
 min_turning_radius: 0.0
 footprint_model: 
  type: "polygon"


  vertices: [[0.1, -0.1], #1)[0.4, -0.4]    2)[0.1, -0.1]     3)[0.1, -0.1]     4)[0.1, -0.1]     5)[0.1, -0.1]
            [-0.1, -0.1], #1)[-0.4, -0.4]   2)[-0.1, -0.1]    3)[-0.1, -0.1]    4)[-0.1, -0.1]    5)[-0.1, -0.1]
            [-0.1, 0.1],  #1)[-0.4, 0.4]    2)[-0.1, 0.1]     3)[-0.1, 0.1]     4)[-0.1, 0.1]     5)[-0.1, 0.1]
            [0.1, 0.1]]   #1)[0.4, 0.4]     2)[0.1, 0.1]      3)[0.1, 0.1]      4)[0.1, 0.1]      5)[0.1, 0.1]
          
 # GoalTolerance

 xy_goal_tolerance: 0.1  #1)0.15   2)0.15    3)0.18    4)0.18    4)0.1
 yaw_goal_tolerance: 0.1 #1)0.15   2)0.15    3)0.18    4)0.18    4)0.1
 free_goal_vel: False     
    
 # Obstacles
    
 min_obstacle_dist: 0.20                    #1)0.10   2)0.10    3)0.15    4)0.35    5)0.20
 include_costmap_obstacles: True            
 costmap_obstacles_behind_robot_dist: 1.0   #1)1.0    2)1.0     3)1.0     4)1.0     5)1.0
 obstacle_poses_affected: 20                #1)20     2)20      3)20      4)20      5)20
 costmap_converter_plugin: "" 
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5                  #1)5.0    2)5       3)5       4)5       5)5
 inflation_dist: 0.1                        #1)0.1    2)0.1     3)0.4     4)0.1     5)0.1
 include_dynamic_obstacles: false

 # Optimization
    
 no_inner_iterations: 3                   
 no_outer_iterations: 2 
 optimization_activate: True
 optimization_verbose: false
 penalty_epsilon: 0.04 
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 200.0 
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 100 
 weight_dynamic_obstacle: 10 
 selection_alternative_time_cost: False 

 # Homotopy Class Planner

 enable_homotopy_class_planning: False 
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1